"""RQ-QS-07A-E1-S -- W Structural Invalidation Stop (2026-10-01, critic+user-
specified). The ONE allowed follow-up to E1 -- per critic's exact framing:
"Does a structurally meaningful stop, defined from the W setup itself, allow
the observed opportunity to survive long enough to monetize?"

Formally demotes S1b/"prior day's low" as a universal stop convention (user's
own point, critic agreed): that was a convenient generic placeholder adopted
when no stop had been defined yet, not a researched truth -- it fits a
breakout-from-a-base thesis (O'Neil/Minervini: invalidation = breaking the
base/pivot structure) far better than it fits W, which isn't a classical
base-breakout setup at all (weak trend state + decline + recovery). The stop
should correspond to what would invalidate the W RECOVERY thesis specifically,
not a borrowed convention.

EVERYTHING ELSE FROZEN, per critic's exact instruction -- only the stop
changes:
  - same W definition (CG1-frozen, reused not re-derived)
  - same T decision (EOD-confirmed)
  - same T+1 open entry
  - same 15-day horizon (MAX_TRACK_DAYS)
  - same exit engine (STOP_R=-1.0, running MFE/MAE, corp-action truncation)
  - same 1.0% minimum-risk data-integrity floor (NOT a tuned threshold, same
    exclusion category as E1 -- see E1's own disclosure)
  - same capacity-constrained evaluation methodology
  - NO new W threshold, NO new predictor, NO S revisited (critic: "S has
    already consumed enough research bandwidth")

THE ONLY CHANGE -- the stop: the structural low of the SAME 10-day window
that already defines `decline_from_high10d_pct` (W's own decline-depth
component) -- i.e. `min(Low)` over the trailing 10 trading days ending at T
inclusive, NOT T's own low alone. Reuses an already-computed reference
window, not a newly-tuned lookback -- per critic's explicit instruction
("operationally, start with the existing 10-day decline window... no
optimization of the structural lookback... we don't test 5D/10D/15D/20D/30D
until something looks good"). Mechanically guaranteed to be equal-to-or-
wider than E1's stop (T's own low is one of the 10 values the min() is taken
over), directly testing whether E1's tightness diagnosis was the real cause.

MANDATORY RISK-GEOMETRY AUDIT (critic's explicit requirement, not optional):
report the initial-risk distribution (median/P75/P90) alongside every
outcome metric -- must confirm this hasn't silently become a disguised
positional trade (7-10%+ risk, long hold duration) before any mean-R claim
is trusted. This is now a standing discipline for this whole research
line: extreme R values can be generated by pathological denominator
geometry, so risk geometry must be audited BEFORE any headline R-based
result is trusted, not only after something looks suspiciously good.

DECISION RULE (pre-declared, not re-litigated after seeing results):
  - If this materially improves monetization -> W earns ONE more stage:
    define an actual entry trigger and validate it chronologically (an
    OOS/holdout pass, mirroring S's own CG3-H/P5 treatment).
  - If still poor -> bank "W contains genuine exceptional opportunity, but
    the first standalone entry construct does not produce a viable
    short-swing trade under structurally meaningful risk" and move to a
    DIFFERENT research-board hypothesis. NO third W stop attempted.

2025-26 regime weakening will very likely reproduce here too (already
confirmed 3 times independently) -- reported, per critic's explicit
instruction NOT investigated further ("we've already spent enough on that
phenomenon").
"""
import sys, os
sys.path.insert(0, '/Users/mdubey/workspace/personal/my-utilities/md-swing-scanner')
os.chdir('/Users/mdubey/workspace/personal/my-utilities/md-swing-scanner')
import json
import numpy as np
import pandas as pd
from backtest import load, daily_pivots
from risk_of_ruin import capacity_constrained_backtest

OUT_DIR = "swing_qs_07a"
STOP_R = -1.0
MAX_TRACK_DAYS = 15
MIN_RISK_PCT = 1.0  # same data-integrity floor as E1, unchanged
STRUCTURAL_LOOKBACK = 10  # SAME window as decline_from_high10d_pct -- not re-optimized
CAPACITY_SWEEP = (3, 5, 10, 20, 50)

print("Loading the frozen W population (identical to E1, reused not re-derived)...", flush=True)
mech = pd.read_csv(f"{OUT_DIR}/weak_state_mechanism_features.csv", parse_dates=["date"])
state = pd.read_csv(f"{OUT_DIR}/trend_state_anatomy.csv", parse_dates=["date"])[["ticker", "date", "decile"]]
with open(f"{OUT_DIR}/frozen_candidate_spec.json") as f:
    DECLINE_MEDIAN = json.load(f)["decline_from_high10d_pct_median_weak_state"]

d0 = mech.merge(state, on=["ticker", "date"])
w_events = d0[(d0.decile == 0) & (d0.decline_from_high10d_pct <= DECLINE_MEDIAN) & (d0.ret_1d >= 0)].copy()
print(f"W population: {len(w_events):,} events, {w_events.ticker.nunique():,} tickers")

print("\nWalking forward from T+1's open, stop = structural 10-day low (not T's own low)...", flush=True)
cache = {}
recs = []
n_tighter_than_e1 = 0
for n, (t, sub) in enumerate(w_events.groupby("ticker", sort=False)):
    if n % 300 == 0:
        print(f"  {n}/{w_events.ticker.nunique()}", flush=True)
    if t not in cache:
        try:
            cache[t] = load(t, daily_pivots)
        except FileNotFoundError:
            cache[t] = None
    idf = cache[t]
    if idf is None:
        continue
    idx = idf.index
    for r in sub.itertuples():
        if r.date not in idx:
            continue
        pos_t = idx.get_loc(r.date)
        pos_entry = pos_t + 1
        if pos_entry >= len(idx):
            continue
        entry_row = idf.iloc[pos_entry]
        entry_price = entry_row.Open
        structural_low = idf.Low.iloc[max(0, pos_t - STRUCTURAL_LOOKBACK + 1):pos_t + 1].min()
        t_low = idf.Low.iloc[pos_t]
        if structural_low > t_low + 1e-9:
            # should be mathematically impossible (t_low is one of the values min()'d over) -- integrity check
            raise AssertionError(f"structural_low > t_low for {t} {r.date}: {structural_low} > {t_low}")
        if structural_low < t_low - 1e-9:
            n_tighter_than_e1 += 1
        stop_price = structural_low
        if pd.isna(entry_price) or pd.isna(stop_price) or entry_price <= stop_price:
            continue
        initial_risk_pct = (entry_price - stop_price) / entry_price * 100
        if initial_risk_pct < MIN_RISK_PCT:
            continue

        running_mfe, running_mae = -float("inf"), float("inf")
        stopped_by_day = None
        truncated = False
        day_vals = {}
        for d in range(1, MAX_TRACK_DAYS + 1):
            k = pos_entry + (d - 1)
            if k >= len(idx) or idf.iloc[k].corp_action_day or truncated:
                truncated = True
                day_vals[d] = (None, running_mfe if running_mfe != -float("inf") else None,
                                 running_mae if running_mae != float("inf") else None)
                continue
            row = idf.iloc[k]
            close_r = (row.Close / entry_price - 1) * 100 / initial_risk_pct
            high_r = (row.High / entry_price - 1) * 100 / initial_risk_pct
            low_r = (row.Low / entry_price - 1) * 100 / initial_risk_pct
            running_mfe = max(running_mfe, high_r)
            running_mae = min(running_mae, low_r)
            if stopped_by_day is None and low_r <= STOP_R:
                stopped_by_day = d
            day_vals[d] = (close_r, running_mfe, running_mae)

        close15, mfe15, mae15 = day_vals[MAX_TRACK_DAYS]
        final_r = STOP_R if stopped_by_day is not None else close15
        if final_r is None:
            continue
        gb = ((mfe15 - close15) / mfe15 * 100) if (mfe15 is not None and close15 is not None and mfe15 > 0) else None
        hold_days = stopped_by_day if stopped_by_day is not None else MAX_TRACK_DAYS
        exit_i = min(pos_entry + hold_days - 1, len(idx) - 1)
        recs.append(dict(
            ticker=t, trigger_date=r.date, entry_date=idx[pos_entry], exit_date=idx[exit_i],
            entry_price=entry_price, stop_price=stop_price, initial_risk_pct=initial_risk_pct,
            stopped_by_day=stopped_by_day, hold_days=hold_days, final_r=final_r,
            close_r_d3=day_vals[3][0], close_r_d5=day_vals[5][0], close_r_d10=day_vals[10][0], close_r_d15=close15,
            mfe_d1=day_vals[1][1], mfe_d3=day_vals[3][1], mfe_d5=day_vals[5][1], mfe_d10=day_vals[10][1],
            mae_d15=mae15, giveback_pct=gb,
        ))

trades = pd.DataFrame(recs)
trades.to_csv(f"{OUT_DIR}/e1s_structural_stop_trades.csv", index=False)
print(f"\n{len(trades):,} trades resolved (of {len(w_events):,} W events)")
print(f"Integrity check: structural stop was strictly wider than E1's T-low in "
      f"{n_tighter_than_e1:,} of {len(trades):,} resolved trades ({n_tighter_than_e1/len(trades)*100:.1f}%) "
      f"-- never narrower, by construction")


def win_rate_stack(r):
    r = r.dropna()
    winners_meaningful = r[r >= 0.25]
    payoff = winners_meaningful.mean() / abs(r[r < 0].mean()) if (r < 0).any() and len(winners_meaningful) else np.nan
    return dict(n=len(r), mean_r=r.mean(), median_r=r.median(),
                 pct_gross_positive=(r > 0).mean() * 100, pct_meaningful=(r >= 0.25).mean() * 100,
                 pct_quality=(r >= 0.5).mean() * 100, pct_full_r=(r >= 1.0).mean() * 100, payoff_ratio=payoff)


print(f"\n{'='*115}\nMANDATORY RISK-GEOMETRY AUDIT (before trusting any outcome number)\n{'='*115}")
risk = trades.initial_risk_pct
print(f"initial_risk_pct: median={risk.median():.2f}%  P75={np.percentile(risk,75):.2f}%  "
      f"P90={np.percentile(risk,90):.2f}%  max={risk.max():.2f}%  min={risk.min():.2f}%")
print(f"hold_days: median={trades.hold_days.median():.1f}  P75={np.percentile(trades.hold_days,75):.1f}  "
      f"%held the full 15 days (never stopped)={100*(trades.stopped_by_day.isna()).mean():.1f}%")
print(f"-- for comparison, E1's own risk/hold geometry: median risk_pct=3.37%, stop rate=77.4% --")

print(f"\n{'='*115}\nWIN-RATE STACK -- structural-stop construct\n{'='*115}")
stats = win_rate_stack(trades.final_r)
print(f"n={stats['n']:,}  mean_R={stats['mean_r']:+.4f}  median_R={stats['median_r']:+.4f}")
print(f"win-rate stack: gross>0={stats['pct_gross_positive']:.1f}%  >=0.25R={stats['pct_meaningful']:.1f}%  "
      f">=0.5R={stats['pct_quality']:.1f}%  >=1.0R={stats['pct_full_r']:.1f}%  payoff={stats['payoff_ratio']:.2f}")
print(f"stop rate: {trades.stopped_by_day.notna().mean()*100:.1f}%  (E1's was 77.4%)")

print(f"\n{'='*115}\nSECONDARY -- D3/D5/D10/D15 close, MFE, giveback (does opportunity remain, is it captured)\n{'='*115}")
for d in [3, 5, 10, 15]:
    print(f"  close_r D{d}: median={trades[f'close_r_d{d}'].median():+.3f}R")
for d in [1, 3, 5, 10]:
    print(f"  mfe D{d}: median={trades[f'mfe_d{d}'].median():+.3f}R")
print(f"  mae D15: median={trades.mae_d15.median():+.3f}R")
gb = trades.giveback_pct.dropna()
print(f"  giveback: median={gb.median():.1f}%  (n={len(gb):,})  %100%-giveback={(gb>=100).mean()*100:.1f}%")

print(f"\n{'='*115}\nYEAR-BY-YEAR (never pooled -- reported, not investigated per critic's instruction)\n{'='*115}")
trades["year"] = trades.trigger_date.dt.year
for y in sorted(trades.year.unique()):
    yr = trades[trades.year == y]
    if len(yr) < 30:
        print(f"  {y}: n={len(yr)} -- too thin, skipped")
        continue
    print(f"  {y}: n={len(yr):,}  mean_R={yr.final_r.mean():+.3f}  gross>0={100*(yr.final_r>0).mean():.1f}%")

print(f"\n{'='*115}\nCAPACITY-CONSTRAINED (risk_of_ruin.py, FCFS, no ranking)\n{'='*115}")
cc_trades = trades[["entry_date", "exit_date", "final_r"]].dropna().rename(columns={"final_r": "r_multiple"})
for n_slots in CAPACITY_SWEEP:
    res = capacity_constrained_backtest(cc_trades, n_slots)
    print(f"  max_concurrent={n_slots:3d}: n_admitted={res['n_admitted']:,}/{res['n_total']:,}  "
          f"cumulative_R={res['cumulative_r']:+.1f}  max_DD={res['max_drawdown_r']:.1f}")
print(f"\n  -- for comparison, E1's own capacity sweep --")
print("  max_concurrent=  5: cumulative_R=-425.6   max_concurrent= 10: cumulative_R=-638.9")

print("\nDONE")
